# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Quarterly Dependency Upgrade
on:
  schedule:
    - cron: 35 15 * * *

jobs:
  create_issue:
    name: Bump Facebook SDK
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Bump Facebook SDK
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "renaudboulard"
          labels: "bookings"
          title: "Bump Facebook SDK"
          body: |
            ### How

            - [ ] Bump the SDK to the [latest version](https://github.com/facebook/facebook-ios-sdk/releases)
            - [ ] Do code migration if required
            - [ ] Test (Staging and Production)
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}